### ISSUE TITLE
Git error when calling v1

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/planemo-ci-action#45]
Hi there and thanks for this great action!

When calling it like:

```
    - name: Fake a Planemo run to update cache
      uses: galaxyproject/planemo-ci-action@v1
      id: discover
      with:
        create-cache: ${{ steps.cache-pip.outputs.cache-hit != 'true' || steps.cache-planemo.outputs.cache-hit != 'true' }}
        galaxy-fork: ${{ env.GALAXY_FORK }}
        galaxy-branch: ${{ env.GALAXY_BRANCH }}
        max-chunks: ${{ env.MAX_CHUNKS }}
        python-version: ${{ matrix.python-version }}
```

(call that I think we haven't changed since the last time it worked, Feb 16th)

we now get:

```
galaxy.util.commands WARNING: Passing program arguments as a string may be a security hazard if combined with untrusted input
cd '/home/runner/_work/container-galaxy-sc-tertiary/container-galaxy-sc-tertiary' && git diff --name-only 'origin/master...' --
Traceback (most recent call last):
  File "/home/runner/_work/_tool/Python/3.8.16/x64/bin/planemo", line 8, in <module>
    sys.exit(planemo())
  File "/home/runner/_work/_tool/Python/3.8.16/x64/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/runner/_work/_tool/Python/3.8.16/x64/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/runner/_work/_tool/Python/3.8.16/x64/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/runner/_work/_tool/Python/3.8.16/x64/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/runner/_work/_tool/Python/3.8.16/x64/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/_work/_tool/Python/3.8.16/x64/lib/python3.8/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/runner/_work/_tool/Python/3.8.16/x64/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/_work/_tool/Python/3.8.16/x64/lib/python3.8/site-packages/planemo/cli.py", line 102, in handle_blended_options
    return f(*args, **kwds)
  File "/home/runner/_work/_tool/Python/3.8.16/x64/lib/python3.8/site-packages/planemo/commands/cmd_ci_find_repos.py", line 30, in cli
    paths = filter_paths(ctx, raw_paths, path_type="repo", **kwds)
  File "/home/runner/_work/_tool/Python/3.8.16/x64/lib/python3.8/site-packages/planemo/ci.py", line 28, in filter_paths
    diff_files = git.diff(ctx, cwd, changed_in_commit_range)
  File "/home/runner/_work/_tool/Python/3.8.16/x64/lib/python3.8/site-packages/planemo/git.py", line 108, in diff
    stdout, _ = io.communicate(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True)
  File "/home/runner/_work/_tool/Python/3.8.16/x64/lib/python3.8/site-packages/planemo/io.py", line 52, in communicate
    raise RuntimeError(msg)
RuntimeError: Problem executing commands cd '/home/runner/_work/container-galaxy-sc-tertiary/container-galaxy-sc-tertiary' && git diff --name-only 'origin/master...' -- - (, fatal: origin/master...HEAD: no merge base
)
```

any ideas of what could be the issue? This is triggered by a commit once merged on the main working (develop, not main) branch. Thanks!

**Comment by pcm32** [comment]
Thanks, no, we haven't renamed the default branch AFAIK, but I will check. 

The whole run is: https://github.com/ebi-gene-expression-group/container-galaxy-sc-tertiary/actions/runs/4569420328/jobs/8073493349#step:21:373

**Comment by pcm32** [comment]
This is the last working run https://github.com/ebi-gene-expression-group/container-galaxy-sc-tertiary/actions/runs/4194383004 - for the previous merge to the default branch (same branch).

**Comment by nsoranzo** [comment]
But you are using `develop` not `master`, right?

**Comment by pcm32** [comment]
Yes.

**Comment by pcm32** [comment]
Funny, a re-run of the same actions seems to fail now on the same step with a different error:

```
galaxy.web_stack INFO 2023-04-12 14:49:46,940 [pN:main,p:4559,tN:MainThread] Galaxy server instance 'main' is running
Starting server in PID 4559.
serving on http://127.0.0.1:42237/

+ GITHUB_EVENT_NAME=push
+ GITHUB_REF=refs/heads/develop
+ '[' '' == '' ']'
+ '[' setup == setup ']'
+ '[' push = push ']'
+ case "$GITHUB_REF" in
+ git fetch origin main
fatal: not a git repository (or any parent up to mount point /home/runner)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
+ git fetch origin master
fatal: not a git repository (or any parent up to mount point /home/runner)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Error: Process completed with exit code 128.
```

whole stack at:

https://github.com/ebi-gene-expression-group/container-galaxy-sc-tertiary/actions/runs/4569420328/jobs/8289717836#step:21:587

**Comment by pcm32** [comment]
I suspect that this might be down to my deploy github action was not checking out the code before the fake planemo run, differently to the PR behaviour. It would make sense with the github error, testing now...

**Comment by pcm32** [comment]
Yes, adding an actions/checkout of the tools code before the fake planemo run fixed this https://github.com/ebi-gene-expression-group/container-galaxy-sc-tertiary/pull/290/files#diff-4f9e38227ed64fefb17f4668a7ac4ab55b6149994d5ac2fd96182d5958479b54R65. Funnily, this was working without a tools checkout (at least for the fake planemo run) before mid February.
